// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package models

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (CandleInfo) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*CandleInfo) UnmarshalJSON([]byte) error        { return nil }
func (CandleInfo) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*CandleInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CandleInfo *CandleInfo

func (ExecuteRequest) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*ExecuteRequest) UnmarshalJSON([]byte) error        { return nil }
func (ExecuteRequest) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*ExecuteRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ExecuteRequest *ExecuteRequest

func (ExecuteResponse) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*ExecuteResponse) UnmarshalJSON([]byte) error        { return nil }
func (ExecuteResponse) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*ExecuteResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ExecuteResponse *ExecuteResponse

func (Key) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*Key) UnmarshalJSON([]byte) error        { return nil }
func (Key) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*Key) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Key *Key

func (Record) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*Record) UnmarshalJSON([]byte) error        { return nil }
func (Record) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*Record) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Record *Record
